name: mobil_habit_tracker
description: A modern, minimalist dark-themed habit tracker mobile application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.6

  # Local storage / persistence
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Local notifications
  flutter_local_notifications: ^21.0.0
  timezone: ^0.11.0

  # Utilities
  uuid: ^4.5.3
  intl: ^0.20.2
  flutter_animate: ^4.2.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # Required to regenerate habit_model.g.dart if model changes
  hive_generator: ^2.0.1
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "appLogo_scaled.png"
  adaptive_icon_background: "#1C1A27"
  adaptive_icon_foreground: "appLogo_scaled.png"

flutter:
  uses-material-design: true
